version: '3.8'

services:
  auth-service:
    container_name: dev-auth-service
    build:
      context: .
      dockerfile: apps/auth-service/Dockerfile
      target: development
    ports:
      - "3001:3001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/auth-service/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - INFISICAL_API_URL=http://ops-infisical:8080
      - INFISICAL_TOKEN=${INFISICAL_TOKEN_AUTH_SERVICE}
    env_file:
      - apps/auth-service/.env

  user-service:
    container_name: dev-user-service
    build:
      context: .
      dockerfile: apps/user-service/Dockerfile
      target: development
    ports:
      - "3002:3002"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/user-service/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3002
      - INFISICAL_API_URL=http://ops-infisical:8080
      - INFISICAL_TOKEN=${INFISICAL_TOKEN_USER_SERVICE}
    env_file:
      - apps/user-service/.env

  web-portal:
    container_name: dev-web-portal
    build:
      context: .
      dockerfile: apps/web-portal/Dockerfile
      target: development
    ports:
      - "3000:3000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/apps/web-portal/node_modules
      - /usr/src/app/apps/web-portal/.next
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOSTNAME=0.0.0.0
      - INFISICAL_API_URL=http://ops-infisical:8080
      - INFISICAL_TOKEN=${INFISICAL_TOKEN_WEB_PORTAL}
    env_file:
      - apps/web-portal/.env
    depends_on:
      - auth-service
      - user-service

  rabbitmq:
    container_name: dev-rabbitmq
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"     # AMQP
      - "15672:15672"   # Management UI
    restart: always

networks:
  default:
    name: ops_default
    external: true

